/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Ingredient, RecipeFormData, RecipeSummary } from "./global/types";
export { Ingredient, RecipeFormData, RecipeSummary } from "./global/types";
export namespace Components {
    /**
     * `category-filter` renders a row of selectable chips (categories/cuisines).
     * `categories` is passed in as a JSON-serializable array of strings, and
     * `activeCategory` reflects the currently selected one (or empty for "All").
     * The consuming app owns the actual filtering logic.
     */
    interface CategoryFilter {
        /**
          * Currently active category, empty string means "All".
          * @default ''
         */
        "activeCategory": string;
        /**
          * Available category labels to render as chips.
          * @default []
         */
        "categories": string[];
    }
    /**
     * `favorite-button` is a standalone, stateless toggle. It never owns the
     * favorite state itself — the consuming app passes in `active` as a prop
     * and listens for `favoriteToggle` to update its own store. This lets the
     * same component be reused inside `recipe-card` and independently on the
     * recipe detail page.
     */
    interface FavoriteButton {
        /**
          * Whether this recipe is currently favorited.
          * @default false
         */
        "active": boolean;
        /**
          * Optional size variant for use in different contexts (card vs. detail page).
          * @default 'sm'
         */
        "size": 'sm' | 'lg';
    }
    /**
     * `ingredient-list` renders a recipe's ingredients on the detail page.
     * Accepts a JSON-serializable array of `{ name, quantity? }`.
     */
    interface IngredientList {
        /**
          * @default []
         */
        "ingredients": Ingredient[];
    }
    /**
     * `meal-plan-slot` represents ONE day in the weekly planner. The consuming
     * SvelteKit app renders 7 of these in a grid (one per day) and owns the
     * actual week state — this component is a dumb, reusable cell: it shows
     * whichever recipe (if any) is assigned to `day`, and emits events when
     * the user wants to assign or remove one. Deliberately NOT a whole-week
     * component, so it stays reusable outside this exact feature and keeps
     * state management centralized in the app.
     */
    interface MealPlanSlot {
        /**
          * The recipe currently assigned to this day, or null if empty. Passed in as a prop by the app.
          * @default null
         */
        "assignedRecipe": RecipeSummary | null;
        /**
          * Day label this slot represents, e.g. "Monday".
          * @default ''
         */
        "day": string;
    }
    /**
     * `rating-badge` shows a difficulty indicator. Public-API recipes (e.g. from
     * TheMealDB) don't include this data, so the consuming app should only
     * render this for user-created recipes where difficulty was captured via
     * `recipe-form`.
     */
    interface RatingBadge {
        /**
          * @default 'easy'
         */
        "difficulty": 'easy' | 'medium' | 'hard';
    }
    /**
     * `recipe-card` displays a single recipe summary for use in grids, search
     * results, and favorites lists. It composes `favorite-button` and
     * `rating-badge` internally, but the actual favorite/rating state is always
     * owned by the consuming app — this component is purely presentational and
     * communicates via events.
     */
    interface RecipeCard {
        /**
          * Recipe title.
          * @default 'Untitled recipe'
         */
        "cardTitle": string;
        /**
          * Optional category/cuisine label, e.g. "Dessert" or "Italian".
         */
        "category"?: string;
        /**
          * Optional difficulty, only meaningful for user-created recipes.
         */
        "difficulty"?: 'easy' | 'medium' | 'hard';
        /**
          * Recipe thumbnail image URL.
          * @default ''
         */
        "image": string;
        /**
          * Whether this recipe is currently in the user's favorites.
          * @default false
         */
        "isFavorite": boolean;
        /**
          * Whether this recipe was created by the user (vs. sourced from the API).
          * @default false
         */
        "isUserCreated": boolean;
        /**
          * Unique identifier of the recipe, passed back in emitted events.
         */
        "recipeId": string;
    }
    /**
     * `recipe-form` handles add/edit for user-created recipes. Validation is
     * performed inside the component (title/image/category/ingredients/
     * instructions all required, at least one ingredient), and only a fully
     * valid `RecipeFormData` payload is ever emitted via `formSubmit`. The app
     * is responsible for persistence (localStorage) — this component has no
     * knowledge of how/where data is stored.
     * A named slot (`extra-fields`) lets the consuming app inject additional
     * form fields (e.g. prep time, servings) without forking this component.
     */
    interface RecipeForm {
        /**
          * Pass existing recipe data to switch the form into edit mode.
         */
        "initialData"?: RecipeFormData;
    }
    /**
     * `recipe-search` is a controlled-ish search input. It keeps its own draft
     * text as internal state for responsive typing, but never owns the "actual"
     * search query — it emits `searchSubmit` on enter/button click, and also a
     * debounced `searchChange` while typing, so the app can decide whether it
     * wants live search or submit-triggered search.
     */
    interface RecipeSearch {
        /**
          * Debounce delay in ms for the live `searchChange` event.
          * @default 350
         */
        "debounceMs": number;
        /**
          * @default 'Search recipes…'
         */
        "placeholder": string;
        /**
          * Initial/controlled value from the app (e.g. restored from URL query params).
          * @default ''
         */
        "value": string;
    }
}
export interface CategoryFilterCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCategoryFilterElement;
}
export interface FavoriteButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFavoriteButtonElement;
}
export interface MealPlanSlotCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMealPlanSlotElement;
}
export interface RecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeCardElement;
}
export interface RecipeFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeFormElement;
}
export interface RecipeSearchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRecipeSearchElement;
}
declare global {
    interface HTMLCategoryFilterElementEventMap {
        "filterChange": { category: string };
    }
    /**
     * `category-filter` renders a row of selectable chips (categories/cuisines).
     * `categories` is passed in as a JSON-serializable array of strings, and
     * `activeCategory` reflects the currently selected one (or empty for "All").
     * The consuming app owns the actual filtering logic.
     */
    interface HTMLCategoryFilterElement extends Components.CategoryFilter, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCategoryFilterElementEventMap>(type: K, listener: (this: HTMLCategoryFilterElement, ev: CategoryFilterCustomEvent<HTMLCategoryFilterElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCategoryFilterElementEventMap>(type: K, listener: (this: HTMLCategoryFilterElement, ev: CategoryFilterCustomEvent<HTMLCategoryFilterElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCategoryFilterElement: {
        prototype: HTMLCategoryFilterElement;
        new (): HTMLCategoryFilterElement;
    };
    interface HTMLFavoriteButtonElementEventMap {
        "favoriteToggle": { nextValue: boolean };
    }
    /**
     * `favorite-button` is a standalone, stateless toggle. It never owns the
     * favorite state itself — the consuming app passes in `active` as a prop
     * and listens for `favoriteToggle` to update its own store. This lets the
     * same component be reused inside `recipe-card` and independently on the
     * recipe detail page.
     */
    interface HTMLFavoriteButtonElement extends Components.FavoriteButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFavoriteButtonElementEventMap>(type: K, listener: (this: HTMLFavoriteButtonElement, ev: FavoriteButtonCustomEvent<HTMLFavoriteButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFavoriteButtonElementEventMap>(type: K, listener: (this: HTMLFavoriteButtonElement, ev: FavoriteButtonCustomEvent<HTMLFavoriteButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFavoriteButtonElement: {
        prototype: HTMLFavoriteButtonElement;
        new (): HTMLFavoriteButtonElement;
    };
    /**
     * `ingredient-list` renders a recipe's ingredients on the detail page.
     * Accepts a JSON-serializable array of `{ name, quantity? }`.
     */
    interface HTMLIngredientListElement extends Components.IngredientList, HTMLStencilElement {
    }
    var HTMLIngredientListElement: {
        prototype: HTMLIngredientListElement;
        new (): HTMLIngredientListElement;
    };
    interface HTMLMealPlanSlotElementEventMap {
        "slotAssignRequest": { day: string };
        "slotRemove": { day: string; recipeId: string };
    }
    /**
     * `meal-plan-slot` represents ONE day in the weekly planner. The consuming
     * SvelteKit app renders 7 of these in a grid (one per day) and owns the
     * actual week state — this component is a dumb, reusable cell: it shows
     * whichever recipe (if any) is assigned to `day`, and emits events when
     * the user wants to assign or remove one. Deliberately NOT a whole-week
     * component, so it stays reusable outside this exact feature and keeps
     * state management centralized in the app.
     */
    interface HTMLMealPlanSlotElement extends Components.MealPlanSlot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMealPlanSlotElementEventMap>(type: K, listener: (this: HTMLMealPlanSlotElement, ev: MealPlanSlotCustomEvent<HTMLMealPlanSlotElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMealPlanSlotElementEventMap>(type: K, listener: (this: HTMLMealPlanSlotElement, ev: MealPlanSlotCustomEvent<HTMLMealPlanSlotElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMealPlanSlotElement: {
        prototype: HTMLMealPlanSlotElement;
        new (): HTMLMealPlanSlotElement;
    };
    /**
     * `rating-badge` shows a difficulty indicator. Public-API recipes (e.g. from
     * TheMealDB) don't include this data, so the consuming app should only
     * render this for user-created recipes where difficulty was captured via
     * `recipe-form`.
     */
    interface HTMLRatingBadgeElement extends Components.RatingBadge, HTMLStencilElement {
    }
    var HTMLRatingBadgeElement: {
        prototype: HTMLRatingBadgeElement;
        new (): HTMLRatingBadgeElement;
    };
    interface HTMLRecipeCardElementEventMap {
        "cardOpen": { recipeId: string };
        "favoriteToggle": { recipeId: string; nextValue: boolean };
    }
    /**
     * `recipe-card` displays a single recipe summary for use in grids, search
     * results, and favorites lists. It composes `favorite-button` and
     * `rating-badge` internally, but the actual favorite/rating state is always
     * owned by the consuming app — this component is purely presentational and
     * communicates via events.
     */
    interface HTMLRecipeCardElement extends Components.RecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeCardElementEventMap>(type: K, listener: (this: HTMLRecipeCardElement, ev: RecipeCardCustomEvent<HTMLRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeCardElement: {
        prototype: HTMLRecipeCardElement;
        new (): HTMLRecipeCardElement;
    };
    interface HTMLRecipeFormElementEventMap {
        "formSubmit": RecipeFormData;
        "formCancel": void;
    }
    /**
     * `recipe-form` handles add/edit for user-created recipes. Validation is
     * performed inside the component (title/image/category/ingredients/
     * instructions all required, at least one ingredient), and only a fully
     * valid `RecipeFormData` payload is ever emitted via `formSubmit`. The app
     * is responsible for persistence (localStorage) — this component has no
     * knowledge of how/where data is stored.
     * A named slot (`extra-fields`) lets the consuming app inject additional
     * form fields (e.g. prep time, servings) without forking this component.
     */
    interface HTMLRecipeFormElement extends Components.RecipeForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeFormElementEventMap>(type: K, listener: (this: HTMLRecipeFormElement, ev: RecipeFormCustomEvent<HTMLRecipeFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeFormElementEventMap>(type: K, listener: (this: HTMLRecipeFormElement, ev: RecipeFormCustomEvent<HTMLRecipeFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeFormElement: {
        prototype: HTMLRecipeFormElement;
        new (): HTMLRecipeFormElement;
    };
    interface HTMLRecipeSearchElementEventMap {
        "searchChange": { query: string };
        "searchSubmit": { query: string };
    }
    /**
     * `recipe-search` is a controlled-ish search input. It keeps its own draft
     * text as internal state for responsive typing, but never owns the "actual"
     * search query — it emits `searchSubmit` on enter/button click, and also a
     * debounced `searchChange` while typing, so the app can decide whether it
     * wants live search or submit-triggered search.
     */
    interface HTMLRecipeSearchElement extends Components.RecipeSearch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRecipeSearchElementEventMap>(type: K, listener: (this: HTMLRecipeSearchElement, ev: RecipeSearchCustomEvent<HTMLRecipeSearchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRecipeSearchElementEventMap>(type: K, listener: (this: HTMLRecipeSearchElement, ev: RecipeSearchCustomEvent<HTMLRecipeSearchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRecipeSearchElement: {
        prototype: HTMLRecipeSearchElement;
        new (): HTMLRecipeSearchElement;
    };
    interface HTMLElementTagNameMap {
        "category-filter": HTMLCategoryFilterElement;
        "favorite-button": HTMLFavoriteButtonElement;
        "ingredient-list": HTMLIngredientListElement;
        "meal-plan-slot": HTMLMealPlanSlotElement;
        "rating-badge": HTMLRatingBadgeElement;
        "recipe-card": HTMLRecipeCardElement;
        "recipe-form": HTMLRecipeFormElement;
        "recipe-search": HTMLRecipeSearchElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    /**
     * `category-filter` renders a row of selectable chips (categories/cuisines).
     * `categories` is passed in as a JSON-serializable array of strings, and
     * `activeCategory` reflects the currently selected one (or empty for "All").
     * The consuming app owns the actual filtering logic.
     */
    interface CategoryFilter {
        /**
          * Currently active category, empty string means "All".
          * @default ''
         */
        "activeCategory"?: string;
        /**
          * Available category labels to render as chips.
          * @default []
         */
        "categories"?: string[];
        /**
          * Fired when the user picks a different chip.
         */
        "onFilterChange"?: (event: CategoryFilterCustomEvent<{ category: string }>) => void;
    }
    /**
     * `favorite-button` is a standalone, stateless toggle. It never owns the
     * favorite state itself — the consuming app passes in `active` as a prop
     * and listens for `favoriteToggle` to update its own store. This lets the
     * same component be reused inside `recipe-card` and independently on the
     * recipe detail page.
     */
    interface FavoriteButton {
        /**
          * Whether this recipe is currently favorited.
          * @default false
         */
        "active"?: boolean;
        /**
          * Fired on click with the value the app should set the favorite state to. Named `favoriteToggle` (not `toggle`) to avoid colliding with the native browser `ToggleEvent` type used by <details>/popover elements.
         */
        "onFavoriteToggle"?: (event: FavoriteButtonCustomEvent<{ nextValue: boolean }>) => void;
        /**
          * Optional size variant for use in different contexts (card vs. detail page).
          * @default 'sm'
         */
        "size"?: 'sm' | 'lg';
    }
    /**
     * `ingredient-list` renders a recipe's ingredients on the detail page.
     * Accepts a JSON-serializable array of `{ name, quantity? }`.
     */
    interface IngredientList {
        /**
          * @default []
         */
        "ingredients"?: Ingredient[];
    }
    /**
     * `meal-plan-slot` represents ONE day in the weekly planner. The consuming
     * SvelteKit app renders 7 of these in a grid (one per day) and owns the
     * actual week state — this component is a dumb, reusable cell: it shows
     * whichever recipe (if any) is assigned to `day`, and emits events when
     * the user wants to assign or remove one. Deliberately NOT a whole-week
     * component, so it stays reusable outside this exact feature and keeps
     * state management centralized in the app.
     */
    interface MealPlanSlot {
        /**
          * The recipe currently assigned to this day, or null if empty. Passed in as a prop by the app.
          * @default null
         */
        "assignedRecipe"?: RecipeSummary | null;
        /**
          * Day label this slot represents, e.g. "Monday".
          * @default ''
         */
        "day"?: string;
        /**
          * Fired when the user clicks an empty slot — app should open a recipe picker and then update its store.
         */
        "onSlotAssignRequest"?: (event: MealPlanSlotCustomEvent<{ day: string }>) => void;
        /**
          * Fired when the user removes the recipe from this day.
         */
        "onSlotRemove"?: (event: MealPlanSlotCustomEvent<{ day: string; recipeId: string }>) => void;
    }
    /**
     * `rating-badge` shows a difficulty indicator. Public-API recipes (e.g. from
     * TheMealDB) don't include this data, so the consuming app should only
     * render this for user-created recipes where difficulty was captured via
     * `recipe-form`.
     */
    interface RatingBadge {
        /**
          * @default 'easy'
         */
        "difficulty"?: 'easy' | 'medium' | 'hard';
    }
    /**
     * `recipe-card` displays a single recipe summary for use in grids, search
     * results, and favorites lists. It composes `favorite-button` and
     * `rating-badge` internally, but the actual favorite/rating state is always
     * owned by the consuming app — this component is purely presentational and
     * communicates via events.
     */
    interface RecipeCard {
        /**
          * Recipe title.
          * @default 'Untitled recipe'
         */
        "cardTitle"?: string;
        /**
          * Optional category/cuisine label, e.g. "Dessert" or "Italian".
         */
        "category"?: string;
        /**
          * Optional difficulty, only meaningful for user-created recipes.
         */
        "difficulty"?: 'easy' | 'medium' | 'hard';
        /**
          * Recipe thumbnail image URL.
          * @default ''
         */
        "image"?: string;
        /**
          * Whether this recipe is currently in the user's favorites.
          * @default false
         */
        "isFavorite"?: boolean;
        /**
          * Whether this recipe was created by the user (vs. sourced from the API).
          * @default false
         */
        "isUserCreated"?: boolean;
        /**
          * Fired when the card body (not the favorite button) is clicked — app should navigate to the detail page.
         */
        "onCardOpen"?: (event: RecipeCardCustomEvent<{ recipeId: string }>) => void;
        /**
          * Fired when the favorite toggle inside the card is pressed.
         */
        "onFavoriteToggle"?: (event: RecipeCardCustomEvent<{ recipeId: string; nextValue: boolean }>) => void;
        /**
          * Unique identifier of the recipe, passed back in emitted events.
         */
        "recipeId": string;
    }
    /**
     * `recipe-form` handles add/edit for user-created recipes. Validation is
     * performed inside the component (title/image/category/ingredients/
     * instructions all required, at least one ingredient), and only a fully
     * valid `RecipeFormData` payload is ever emitted via `formSubmit`. The app
     * is responsible for persistence (localStorage) — this component has no
     * knowledge of how/where data is stored.
     * A named slot (`extra-fields`) lets the consuming app inject additional
     * form fields (e.g. prep time, servings) without forking this component.
     */
    interface RecipeForm {
        /**
          * Pass existing recipe data to switch the form into edit mode.
         */
        "initialData"?: RecipeFormData;
        "onFormCancel"?: (event: RecipeFormCustomEvent<void>) => void;
        "onFormSubmit"?: (event: RecipeFormCustomEvent<RecipeFormData>) => void;
    }
    /**
     * `recipe-search` is a controlled-ish search input. It keeps its own draft
     * text as internal state for responsive typing, but never owns the "actual"
     * search query — it emits `searchSubmit` on enter/button click, and also a
     * debounced `searchChange` while typing, so the app can decide whether it
     * wants live search or submit-triggered search.
     */
    interface RecipeSearch {
        /**
          * Debounce delay in ms for the live `searchChange` event.
          * @default 350
         */
        "debounceMs"?: number;
        /**
          * Fired (debounced) as the user types.
         */
        "onSearchChange"?: (event: RecipeSearchCustomEvent<{ query: string }>) => void;
        /**
          * Fired immediately on Enter or submit-button click.
         */
        "onSearchSubmit"?: (event: RecipeSearchCustomEvent<{ query: string }>) => void;
        /**
          * @default 'Search recipes…'
         */
        "placeholder"?: string;
        /**
          * Initial/controlled value from the app (e.g. restored from URL query params).
          * @default ''
         */
        "value"?: string;
    }

    interface CategoryFilterAttributes {
        "activeCategory": string;
    }
    interface FavoriteButtonAttributes {
        "active": boolean;
        "size": 'sm' | 'lg';
    }
    interface MealPlanSlotAttributes {
        "day": string;
    }
    interface RatingBadgeAttributes {
        "difficulty": 'easy' | 'medium' | 'hard';
    }
    interface RecipeCardAttributes {
        "recipeId": string;
        "cardTitle": string;
        "image": string;
        "category": string;
        "isFavorite": boolean;
        "isUserCreated": boolean;
        "difficulty": 'easy' | 'medium' | 'hard';
    }
    interface RecipeSearchAttributes {
        "value": string;
        "placeholder": string;
        "debounceMs": number;
    }

    interface IntrinsicElements {
        "category-filter": Omit<CategoryFilter, keyof CategoryFilterAttributes> & { [K in keyof CategoryFilter & keyof CategoryFilterAttributes]?: CategoryFilter[K] } & { [K in keyof CategoryFilter & keyof CategoryFilterAttributes as `attr:${K}`]?: CategoryFilterAttributes[K] } & { [K in keyof CategoryFilter & keyof CategoryFilterAttributes as `prop:${K}`]?: CategoryFilter[K] };
        "favorite-button": Omit<FavoriteButton, keyof FavoriteButtonAttributes> & { [K in keyof FavoriteButton & keyof FavoriteButtonAttributes]?: FavoriteButton[K] } & { [K in keyof FavoriteButton & keyof FavoriteButtonAttributes as `attr:${K}`]?: FavoriteButtonAttributes[K] } & { [K in keyof FavoriteButton & keyof FavoriteButtonAttributes as `prop:${K}`]?: FavoriteButton[K] };
        "ingredient-list": IngredientList;
        "meal-plan-slot": Omit<MealPlanSlot, keyof MealPlanSlotAttributes> & { [K in keyof MealPlanSlot & keyof MealPlanSlotAttributes]?: MealPlanSlot[K] } & { [K in keyof MealPlanSlot & keyof MealPlanSlotAttributes as `attr:${K}`]?: MealPlanSlotAttributes[K] } & { [K in keyof MealPlanSlot & keyof MealPlanSlotAttributes as `prop:${K}`]?: MealPlanSlot[K] };
        "rating-badge": Omit<RatingBadge, keyof RatingBadgeAttributes> & { [K in keyof RatingBadge & keyof RatingBadgeAttributes]?: RatingBadge[K] } & { [K in keyof RatingBadge & keyof RatingBadgeAttributes as `attr:${K}`]?: RatingBadgeAttributes[K] } & { [K in keyof RatingBadge & keyof RatingBadgeAttributes as `prop:${K}`]?: RatingBadge[K] };
        "recipe-card": Omit<RecipeCard, keyof RecipeCardAttributes> & { [K in keyof RecipeCard & keyof RecipeCardAttributes]?: RecipeCard[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `attr:${K}`]?: RecipeCardAttributes[K] } & { [K in keyof RecipeCard & keyof RecipeCardAttributes as `prop:${K}`]?: RecipeCard[K] } & OneOf<"recipeId", RecipeCard["recipeId"], RecipeCardAttributes["recipeId"]>;
        "recipe-form": RecipeForm;
        "recipe-search": Omit<RecipeSearch, keyof RecipeSearchAttributes> & { [K in keyof RecipeSearch & keyof RecipeSearchAttributes]?: RecipeSearch[K] } & { [K in keyof RecipeSearch & keyof RecipeSearchAttributes as `attr:${K}`]?: RecipeSearchAttributes[K] } & { [K in keyof RecipeSearch & keyof RecipeSearchAttributes as `prop:${K}`]?: RecipeSearch[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * `category-filter` renders a row of selectable chips (categories/cuisines).
             * `categories` is passed in as a JSON-serializable array of strings, and
             * `activeCategory` reflects the currently selected one (or empty for "All").
             * The consuming app owns the actual filtering logic.
             */
            "category-filter": LocalJSX.IntrinsicElements["category-filter"] & JSXBase.HTMLAttributes<HTMLCategoryFilterElement>;
            /**
             * `favorite-button` is a standalone, stateless toggle. It never owns the
             * favorite state itself — the consuming app passes in `active` as a prop
             * and listens for `favoriteToggle` to update its own store. This lets the
             * same component be reused inside `recipe-card` and independently on the
             * recipe detail page.
             */
            "favorite-button": LocalJSX.IntrinsicElements["favorite-button"] & JSXBase.HTMLAttributes<HTMLFavoriteButtonElement>;
            /**
             * `ingredient-list` renders a recipe's ingredients on the detail page.
             * Accepts a JSON-serializable array of `{ name, quantity? }`.
             */
            "ingredient-list": LocalJSX.IntrinsicElements["ingredient-list"] & JSXBase.HTMLAttributes<HTMLIngredientListElement>;
            /**
             * `meal-plan-slot` represents ONE day in the weekly planner. The consuming
             * SvelteKit app renders 7 of these in a grid (one per day) and owns the
             * actual week state — this component is a dumb, reusable cell: it shows
             * whichever recipe (if any) is assigned to `day`, and emits events when
             * the user wants to assign or remove one. Deliberately NOT a whole-week
             * component, so it stays reusable outside this exact feature and keeps
             * state management centralized in the app.
             */
            "meal-plan-slot": LocalJSX.IntrinsicElements["meal-plan-slot"] & JSXBase.HTMLAttributes<HTMLMealPlanSlotElement>;
            /**
             * `rating-badge` shows a difficulty indicator. Public-API recipes (e.g. from
             * TheMealDB) don't include this data, so the consuming app should only
             * render this for user-created recipes where difficulty was captured via
             * `recipe-form`.
             */
            "rating-badge": LocalJSX.IntrinsicElements["rating-badge"] & JSXBase.HTMLAttributes<HTMLRatingBadgeElement>;
            /**
             * `recipe-card` displays a single recipe summary for use in grids, search
             * results, and favorites lists. It composes `favorite-button` and
             * `rating-badge` internally, but the actual favorite/rating state is always
             * owned by the consuming app — this component is purely presentational and
             * communicates via events.
             */
            "recipe-card": LocalJSX.IntrinsicElements["recipe-card"] & JSXBase.HTMLAttributes<HTMLRecipeCardElement>;
            /**
             * `recipe-form` handles add/edit for user-created recipes. Validation is
             * performed inside the component (title/image/category/ingredients/
             * instructions all required, at least one ingredient), and only a fully
             * valid `RecipeFormData` payload is ever emitted via `formSubmit`. The app
             * is responsible for persistence (localStorage) — this component has no
             * knowledge of how/where data is stored.
             * A named slot (`extra-fields`) lets the consuming app inject additional
             * form fields (e.g. prep time, servings) without forking this component.
             */
            "recipe-form": LocalJSX.IntrinsicElements["recipe-form"] & JSXBase.HTMLAttributes<HTMLRecipeFormElement>;
            /**
             * `recipe-search` is a controlled-ish search input. It keeps its own draft
             * text as internal state for responsive typing, but never owns the "actual"
             * search query — it emits `searchSubmit` on enter/button click, and also a
             * debounced `searchChange` while typing, so the app can decide whether it
             * wants live search or submit-triggered search.
             */
            "recipe-search": LocalJSX.IntrinsicElements["recipe-search"] & JSXBase.HTMLAttributes<HTMLRecipeSearchElement>;
        }
    }
}
